### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by cjam** [cjam/react-native-spotify-remote#1]
Need to add support for Android.  Worthwhile taking a look at the docs here:

[Auth](https://spotify.github.io/android-sdk/auth-lib/docs/index.html)
[Remote](https://spotify.github.io/android-sdk/app-remote-lib/docs/index.html)

Also, it would be wise to take a gander at how @luisfinkey put his together here: https://github.com/lufinkey/react-native-spotify/tree/master/android

**Comment by AlexLaRochelle** [comment]
@cjam Hi! I'm currently in the last year of my CS degree and I was interested in doing a react native project using you or lufinkey's libraries, and potentially helping you with the Android support. Could you reach out to me via email at alexandre.larochelle4@usherbrooke.ca so that I could explain my "situation" and see what would be feasible regarding the project? Thanks!

**Comment by romchambe** [comment]
Hi @cjam, I am currently working on an app that is already live ([Règlement Radio](https://apps.apple.com/fr/app/r%C3%A8glement-radio/id1297671808)). It is a rap music discovery app. We are now playing the songs on youtube inside our app but I am currently testing a spotify integration using your package on iOS. I'd be interested in helping with Android since I'll probably need that in the weeks to come. Let me know if I can help !

**Comment by cjam** [comment]
hey @romchambe , Great to hear that you might like to help.  There's actually a PR #33 that implements android support that I haven't had a chance to checkout and try to get running yet.  I have an example app in the root of this repo that I use for testing all of the exposed functionality.  My plan was to try and get the sample app running with the android implementation and see if all of the functionality works.  Might be a place to start.  The example app takes a bit to get up and running, but I'm happy to help you get it set up.
