### ISSUE TITLE
Connect implementation for android is actually incorrect

### ISSUE THREAD

**Issue by reteps** [cjam/react-native-spotify-remote#107]
So you may have to undo my previous pull request....

This is sortof a rant, sorry in advance.

The ios connection flow is very simple:

+ Authorize -> returns token
+ Connect -> uses token to connect with remote

The android connect flow is not:
+ Authorize -> calls internal spotify authorize method, making sure that the user is authenticated for the next hour. The access token returned is NOT used

+ Connect -> Checks that authorize was called, then connects to remote WITHOUT access token.

Therefore, the android connection method should be rewritten to make `authorize` optional. Additionally, the connect method for android does not need any token passed to it.

In the light of cross compatibility, however, we want both the android and IOS methods to follow this flow regardless:

```
await remote.authorize() // we want to call this method on android, but not actually do anything
await remote.connect(token) // In android this 'token' is not used, but in ios it is
await remote.playSong()
```

So the ideal way to do this is to add some sort of flag to the authorize method that indicates that we have already authenticated, so we do not need to authenticate again.

**Comment by cjam** [comment]
Hey thanks for the issue and the PR.  I've been busy lately so I'm trying to catch up on some of these issues.  Yea. there is definitely something to be desired about the differences in the iOS and Android libraries.  

My thought originally was that since the session gets returned, it would be able to be persisted and refreshed independently.  Since the Session object is returned from authorize and is a simple json object.  Could the expiry / token be inspected and be used to conditionally call authorize?  Otherwise I think that is where the token refresh endpoint would come in and refresh to the token to be used.  But I haven't ever gotten around to trying that.

**Comment by cjam** [comment]
Cool. Yea I'm open to adjusting things for sure.  One wrinkle is in the iOS side where typically the auth is used to wake spotify up and make sure that it is running so that when you connect to it it will actually work.

**Comment by djwillcaine** [comment]
I was trying to come up with a way to persist the authentication in Android a few days ago, I assumed I could store the refresh token once authenticated and use my endpoint to refresh it, but it turns out the session returned on Android doesn't contain the refresh token. This seems to be a strangely deliberate decision from the Spotify devs.

Only alternative is to use the Spotify Web API for authing.

**Comment by reteps** [comment]
@djwillcaine Thats how I was doing it

**Comment by cjam** [comment]
@reteps did you see issue https://github.com/cjam/react-native-spotify-remote/issues/67  and the subsequent PR https://github.com/cjam/react-native-spotify-remote/pull/68 ?  

@uptotec issued the PR a long time ago but I haven't had a chance to get it integrated as it was a different flow.  But it seems like a different flow is needed for android anyways.

**Comment by reteps** [comment]
I am a little confused about the `swap` endpoint. He mentions it being called, but there are no references to it anywhere in the code from what I can see.

**Comment by reteps** [comment]
But from what I can see, it #68 looks good and if that is merged I can close this.

**Comment by cjam** [comment]
@reteps did you see my comments in #121?

**Comment by cjam** [comment]
This work was finally merged in.
