### ISSUE TITLE
Android INVALID_APP_ID

### ISSUE THREAD

**Issue by jmarkyston** [cjam/react-native-spotify-remote#110]
I know this has probably been asked and answered. I did try some things, but I haven't found an answer that worked yet, and I'm hoping someone can help me out.

- I created a new react native app using `npx react-native init reactnative`
- Then I installed the plugin and added a click event to a button which tries to connect and play a song much like the Usage section of the readme.
- I `cd`ed into `android` and ran `./gradlew signingReport` to get the SHA1.
- I added that to my Spotify dashboard with the app ID "com.reactnative" from build.gradle, etc.
- The rest of my config looks the same as yours other than the fact that I did not add the tokenRefreshURL and tokenSwapURL to the object.

When it tries to connect when I run it on my device, it seems to log into Spotify correctly, but it throws an INVALID_APP_ID error. Any idea what I'm missing?

I'm on Windows 10.

**Comment by cjam** [comment]
I have to admit, I may need to update the usage in the Readme.  Have you looked at the code in the example app?  So are you retrieving a token from spotify directly through their web API?  Otherwise you'll need the token swap / refresh endpoints available for spotify to do the auth for you.

Here's the spot in the example where that's happening:

https://github.com/cjam/react-native-spotify-remote/blob/528e0e93c7648959b28806da5ba7f0078d5911ac/example/AppContext.tsx#L130-L137

You should be able to run the example server if you just provide it with a `.env` file with your apps configuration, see: 

https://github.com/cjam/react-native-spotify-remote/tree/master/example-server

**Comment by jmarkyston** [comment]
I apologize for my ignorance. This is my first time doing anything with SHA1 strings like this. I was confused and using the wrong SHA1 🙄 

I seem to have gotten past that error, and now I'm running into a new one. This time there is no error message. It gives me line 99353, column 57 of index.bundle, but nothing other than that. I wouldn't be surprised if it did have to do with the refresh and swap URLs. 

I figure it's probably worth just closing this issue. Thanks for the reply, and sorry for wasting your time!
