### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by FrankFundel** [cjam/react-native-spotify-remote#40]
Hey,
I have problems connecting with SpotifyRemote. After `var token = await SpotifyAuth.initialize(spotifySDKConfig);` I get an accessToken, but it seems like it is invalid. If I have Spotify already opened I get this error while connecting: `Error: Connection attempt failed.
The operation couldn’t be completed. wamp.error.not_authorized`. If Spotify is closed and then started by my app I do not get an error from connect, but when I try to play a track I get: `Error: Player is not ready`
I cannot find anything about this online, I tried setting playURI in the config still not working.
Maybe someone has an idea.

**Comment by cjam** [comment]
did you include the `app remote` scope when you used initialize?

**Comment by FrankFundel** [comment]
Nope, now it works thank you. I didn't read that as necessary

**Comment by cjam** [comment]
Great news

**Comment by FrankFundel** [comment]
Hey, after updating to the latest release I get the same errors again. I changed nothing else.

**Comment by cjam** [comment]
there were some breaking changes in the latest version.  The config object now takes an array of scopes:

https://github.com/cjam/react-native-spotify-remote/blob/c0a81d7fb4dae4686b713268aa51471188729562/example/AppContext.tsx#L135

I've also deprecated the `initialize` (will be released in the future) function in favor of `authorize`

**Comment by david03g** [comment]
Hi @cjam , 

I've been experiencing this
`Error: Connection attempt failed. The operation couldn’t be completed. wamp.error.not_authorized`
connection issue. It seems like I can only connect one time per authorization with a given acces token. Even after refreshing the token, I get the same error. I have included the app-remote-controll scope in the config. It is strange because I did not have this occur before.
