### ISSUE TITLE
Lost connection to Spotify very often

### ISSUE THREAD

**Issue by pkhien95** [cjam/react-native-spotify-remote#41]
After connecting and playing song successfully, I stop the playback and use some other features of my app for a while, then the remote event `remoteDisconnected` is fired very often. Everytime the remote is disconnected, I have to initialize again (the app will navigate to Spotify to auth and navigate back) despite the access token is still valid. Is there any way I can reconnect to remote without initializing because that will make users feel annoying?

**Comment by cjam** [comment]
@pkhien95 yes, it is unfortunate.  I haven't found a good way around it yet.  

#### TLDR; 
**iOS will background spotify if it is not playing music which will suspend the internal server that handles the remote requests and therefore will disconnect the app remote**

The reason behind it is outlined here: https://github.com/spotify/ios-sdk#frequently-asked-questions .

**Comment by mguay22** [comment]
Hey @cjam - thanks for the awesome work man. I'm wondering if you have any ideas for getting around this? Facing it in my current project where I can play songs from multiple providers (Spotify, SoundCloud, etc). When I switch to a different provider (which uses `react-native-track-player`) - and then I try to play a Spotify song, I get `Player is not ready` message which I assume is caused by this issue.

**Comment by mguay22** [comment]
Actually I was able to get around this the same way in #51 - setting the `react-native-track-player` `iosCategoryOptions` to `['mixWithOthers`]` so that playback doesn't disrupt the Spotify client. Works like a charm. Thanks again for all your work. I plan on starting to contribute to this library as I will be using it heavily in my hobby project.

**Comment by cjam** [comment]
Great work around. Yea. it's a battle to keep iOS from backgrounding spotify.  The OS is pretty aggressive with backgrounding apps to free up resources.
