### ISSUE TITLE
playURI option for auth config doesn't work

### ISSUE THREAD

**Issue by donghee214** [cjam/react-native-spotify-remote#50]
Hi!

I've noticed that the playURI option for the authorize method doesn't appear to be doing anything. I think this is necessary to wake up the Spotify application running in the background, as the connect method will fail to connect except in the situation where music is already playing. Outlined in the ios-sdk, they say to use the authorizeAndPlayURI option to work around this and originally thought playURI option for authorize would be the react-native equivalent

Thanks!

["iOS requires us to define a playURI (as shown in the last step) in order to play music to wake up the Spotify main application. This is an iOS-specific requirement." ](https://developer.spotify.com/documentation/ios/quick-start/)

**Comment by Cal-JChapman** [comment]
I think I'm having the same issue, I'm receiving an error message saying:

Error: Connection attempt failed.
Stream error.
The operation couldn’t be completed. Connection refused

I'm pretty inexperienced so could just be me being stupid but if anyone has a solution / work around it would be greatly appreciated :)

**Comment by cjam** [comment]
Hey sorry for the delay on the response to this.  I haven't been getting notified about new issues in github for some reason.  @donghee214 you are right, in order to make sure spotify is awake and able to receive connections you'll need to use the authorize and play functionality.  This is actually the first screen in the example application so that I could test and verify the various options.

I just ran the example app and can confirm that using a `playURI=""` will resume playback on authentication and that `playUri="someSpotifyTrack"` will start playing *someSpotifyTrack*.  It does seem that the behaviour in Spotify has changed.  This option only seems to have an effect if spotify isn't currently playing anything.  Included below is a small screen recording of the behavior.

![Image 2](https://user-images.githubusercontent.com/1000288/85149125-c94bf380-b205-11ea-8779-d626283b8a50.GIF)


@Cal-JChapman can you confirm that you have some sort of server able to handle the token swap and refresh requests and that you have also created your spotify application and are using the correct Client ID's and secrets?  You may also want to double check if you're passing in your own Api scopes that you have the `remote` scope included.

**Comment by Cal-JChapman** [comment]
@cjam thanks for responding, I've got a token swap and refresh server running, and I found last night that everything works perfectly if I'm already playing a song on Spotify's app on the device, however when I authorise and play on the phone without that it doesn't work? 

When I get it working this sdk is awesome though so thank you :)

**Comment by donghee214** [comment]
@cjam Ah I see, just to confirm it's not expected for the AuthAndPlay to work if spotify is not opened. One would have to have it running in the background (play or paused) for it to initially work?

**Comment by cjam** [comment]
Nope, it should work if spotify is not opened.  I think I might know what is happening.  Spotify's docs around setup are a little fragmented and I haven't had time to update the docs on this project to point to all the appropriate stuff.  

Look at this page https://developer.spotify.com/documentation/ios/quick-start/ 
Specifically the section on **Configure Info.plist**  

Can you confirm that you've added *spotify* to your **LSApplicationQueriesSchemes**

**Comment by donghee214** [comment]
Ah thank you this had fixed my issue!

After following the steps for setting up Info.plist it opens spotify and redirects back after auth!
