### ISSUE TITLE
Request: Expose AppRemote Connection Parameters

### ISSUE THREAD

**Issue by stefangiapantzakis** [cjam/react-native-spotify-remote#58]
Hi,

I was wondering if there was anyway you could provided accessors to the `_appRemote.connectionParameters`?

Spotify seem to recommend disconnecting / reconnecting your AppRemote Connection during app backgrounding and foregrounding and provide this logic on how to do so:
https://github.com/spotify/ios-sdk/blob/403b67cf644faf330312255c2bbf7d838e9ea55f/DemoProjects/SPTLoginSampleAppSwift/SPTLoginSampleAppSwift/AppDelegate.swift#L28

I've currently hacked in an approach to just return the accessToken from `RNSpotifyRemoteAppRemote.m` but this will require making local changes every-time I install my project on a new machine.

**Comment by cjam** [comment]
Hey, good question

I have exposed connect / disconnect through the api:

https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyremoteapi.html#connect 

Right now, when you use `authorize` with the auth module, it will return you back the `SpotifySession` which has the token on it.  https://cjam.github.io/react-native-spotify-remote/interfaces/spotifyauth.html#authorize

You should then be able to use / persist this session and be able to check if the token is still valid so that you can use it to reconnect.
